### ISSUE TITLE
Upgrade OMP to support Java 8

### ISSUE THREAD

**Issue by NathanBaldwin1** [ozone-development/ozp-community-request#15]
Please upgrade OMP to support Java 8

**Comment by jamelen** [comment]
This has been updated as a beta release; awaiting for additional community testing and feedback for official release.
https://github.com/ozoneplatform/owf-framework/releases/tag/v7.17.0

**Comment by jamelen** [comment]
No additional feedback has been received, any new OMP bugs as a result of the JAVA 8 upgrade must be listed as a new issue.
