### ISSUE TITLE
Resolve the mixed content limitation for the OZP.

### ISSUE THREAD

**Issue by fieldsm** [ozone-development/ozp-community-request#17]
The widgets in NGA's Integrated Analytic Environment Analytic Workspace (IAE/AW) depend on their back-end services to deliver what's promised.  In the IAE/AW, the back-end services will work with mixed content (either http: or https:) and this does not pose a problem in OWF.  However, mixed content will not work in OZP, potentially making widgets migrated from IAE/AW to the AML inoperable.   Resolve the mixed content limitation for the OZP.

**Comment by tonyalletag** [comment]
This is a deployment configuration issue not a software issue.
