### ISSUE TITLE
ATL/C3CB Topic #1: Need to know the roadmap or way ahead for Ozone

### ISSUE THREAD

**Issue by Saddisonreed** [ozone-development/ozp-community-request#19]
DISA and other acquisitions shops request clarity on the technical direction for OZP and the migration bridges toward OZP.
- Will OZP accommodate federalized market requirements?
- OWF wrappers?
- How does each OZP release align to IC-ITE DTE web browser standards as well as DoD & SDC browser desktop configurations for Services

Please refer to document for detailed list of questions under this topic

**Comment by Saddisonreed** [comment]
Issue submitted by Nate Baldwin & Michael Hart, DISA

**Comment by jamelen** [comment]
Roadmap discussed on 22 October 2015 GOSS Board Meeting; it is posted at the bottom of the page:
https://github.com/ozone-development/ozp-documentation
