### ISSUE TITLE
ATL/C3CB #3: What are the ROEs for engaging CRADA custodian?

### ISSUE THREAD

**Issue by Saddisonreed** [ozone-development/ozp-community-request#21]
Because of this imminent technology transition of the OZONE OWF codebase to a CRADA, we would like more clarity on the scope and the sustainment model of the CRADA to include how requirements can be passed to the vendor and how it will be paid for.  
(Adam Dooley, MITRE for DI2E)

**Comment by jamelen** [comment]
Per discussions on January 21 GOSS Board Meeting, this issues is closed.
