### ISSUE TITLE
Feature Requests from Tactical Army

### ISSUE THREAD

**Issue by itaran** [ozone-development/ozp-community-request#3]
1. API so that population and updates of the marketplace can be easily automated through scripts.  A manual process for loading each widget is cumbersome, and we are looking for ways to automate this for every deployment of OZP.

2. Means of setting a widget to be automatically bookmarked for ALL users.  We know ahead of time that certain widgets are applicable to all users.  We don't want to make the user hunt for those widgets in the marketplace. They should be available to the user at first logon in the HUD or Webtop.  Ideally, we should be able to automate the marking of widgets as 'automatically available' through above mentioned API.

3. Bring back the concept of administrative users or bring back the concept of groups so that we can designate certain users as adminstrators.  We have widgets that should be hidden from general users and should only be visible to "admin" users.  We need a way to hide them in the marketplace so that only users designated as admins or users that belong to the admin group can see them and bookmark them.

4. Bring back the custom dashboard builder similar to what existed in OWF 7.X

5. Provide the ability to prevent certain widgets from launching outside the webtop.  This could be a good distinction between an "App" and a "Widget".  Apps can be launched anywhere.  The option to prevent a widget from opening outside the webtop could disappear if a widget is classified as a widget when registered with the marketplace.

**Comment by mparizernc** [comment]
Concerning "1" there is currently an API to create listings. You can find documentation for the REST API for creating listings here: https://github.com/ozone-development/ozp-rest/blob/master/docs-external/rest/OZP_listing_createAPI.md

**Comment by tonyalletag** [comment]
It is preferred to have each request in a separate issue.  This way we can address and have conversations specific to each request.  

If we complete a request we would like to test and close that specific issue.
