### ISSUE TITLE
Developer Tutorial

### ISSUE THREAD

**Issue by itaran** [ozone-development/ozp-community-request#4]
This isn't a feature request exactly, but a request nevertheless.

Collate all documentation into concise and COMPLETE documents that include the following
1. Admin Guide
2. Configuration Guide that includes instructions on building OZP from source
3. A Developers Guide - a tutorial that walks a developer step by step through the process of creating a widget and getting it to talk to other widgets through the IWC, to include sending data, mimicking intents, launching other widgets, etc.   This should also spell out all the API calls and functions available to developers.

The developers guide is particularly important.  Some of this information exists scattered across GitHub pages.  Some info does not exist to my knowledge.

**Comment by tonyalletag** [comment]
IWC Developer tutorials have been posted here - http://ozone-development.github.io/ozp-iwc/tutorial/

**Comment by jamelen** [comment]
In response to item 1 and 2 from request documentation is posted here:
https://github.com/ozone-development/ozp-documentation/tree/master/Documentation
In response to item 3, IWC developer tutorials have been posted here:
http://ozone-development.github.io/ozp-iwc/tutorial/
Any additional request should be opened on a new ticket.
