### ISSUE TITLE
Navy Requests

### ISSUE THREAD

**Issue by oneilos77** [ozone-development/ozp-community-request#5]
Navy Top 5 requests:

•	OZP Franchise Store Capability
     o	The Navy requires that an Appstore exist at every end point due to the limitations of bandwidth for deployed vessels.

•	OZP User/Group management
     o	Navy requires users/groups in OZP

•	IWC between OWF/OZP widgets
     o	Navy requires IWC between OWF/OZP widgets

•	Backwards forwards capability OWF/OZP environments
     o	Navy requires OWF widgets moved into OZP environments to function as they did in OWF environment

•	Addition of OWF layouts into OZP
     o	Navy requires layouts from OWF to be in OZP.  Programs of record with complex applications will want to have structured layouts.

**Comment by tonyalletag** [comment]
It is preferred to have each request in a separate issue.  This way we can address and have conversations specific to each request.  

If we complete a request we would like to test and close that specific issue.
