### ISSUE TITLE
Automatic Bookmarking of Widgets

### ISSUE THREAD

**Issue by itaran** [ozone-development/ozp-community-request#6]
Means of setting a widget to be automatically bookmarked for ALL users. We know ahead of time that certain widgets are applicable to all users. We don't want to make the user hunt for those widgets in the marketplace. They should be available to the user at first logon in the HUD or Webtop. Ideally, we should be able to automate the marking of widgets as 'automatically available' through the widget loading API.

**Comment by jamelen** [comment]
Share Folders and use of scripts should satisfy this requirement. Share folders have been implemented with a link that can be emailed or posted on a website, blog or wiki. Future improvements to share folders include an interface to allow the selection of users within OZP and to notify via the common tool notification mechanism.

https://github.com/ozone-development/ozp-documentation/wiki/Share-Bookmarked-Folder
