### ISSUE TITLE
Admin Users

### ISSUE THREAD

**Issue by itaran** [ozone-development/ozp-community-request#7]
Bring back the concept of administrative users or bring back the concept of groups so that we can designate certain users as administrators. We have widgets that should be hidden from general users and should only be visible to "admin" users. We need a way to hide them in the marketplace so that only users designated as admins or users that belong to the admin group can see them and bookmark them.

**Comment by jamelen** [comment]
Per discussion on 21 January GOSS Board Meeting, this issue is merging with issue #11.
